# Seems like vigra isn't really compatible with vs2019
c_compiler:                    # [win]
  - vs2022                     # [win]
cxx_compiler:                  # [win]
  - vs2022                     # [win]
