# Seems like vigra isn't really compatible with new compilers
c_compiler:                    # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]

c_compiler_version:            # [osx]
  - 13                         # [osx]
cxx_compiler_version:          # [osx]
  - 13                         # [osx]

hdf5:
- 1.12.2
- 1.14.0
