{% set version = "1.11.2" %}

package:
  # Package top level name was changed from vigra to libvigra
  # to indicate that only the C library is being built
  # Help is appreciated to rebuild the Python library
  # at which point the package `vigra` can be reintroduced
  # https://github.com/conda-forge/vigra-feedstock/issues/134
  name: libvigra
  version: {{ version }}

source:
  {% set version_tag = "Version-%s" % version.replace(".", "-") %}
  fn: vigra-{{ version_tag }}-src.tar.gz
  url: https://github.com/ukoethe/vigra/archive/{{ version_tag }}.tar.gz
  sha1: 0b48e18b4fa60e39151020fc18acc8bd223b051c
  patches:
    # All patches below are upstreamed, and will be included in the next version
    # C++17/C++20 Compatibility -- https://github.com/ukoethe/vigra/pull/511
    - patches/PR_511.patch
    - patches/nose_to_pytest.patch
    - patches/setuptools.patch
    - patches/555-std_random_shuffle.patch


build:
  # Build number 100 was used to differentiate build 5 and below
  # as a build that no longer supports numpy
  number: 101
  detect_binary_files_with_prefix: true
  # There is a vigra header ./include/vigra/promote_traits.hxx.py
  # That doesn't have a meaningful pyc compilation since this is supposed
  # to be a c-package since we've disabled python compilation
  # https://github.com/conda-forge/vigra-feedstock/issues/134
  skip_compile_pyc:
    - '*'
  run_exports:
    # Seems to change ABI between minor versions
    # https://abi-laboratory.pro/index.php?view=timeline&l=vigra
    - {{ pin_subpackage('libvigra', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - libjpeg-turbo
    - libtiff
    - libpng
    - openexr
    - imath
    - lemon
    - fftw
    - hdf5
    - zlib
    # Only requried for numpy integration which we
    # gave up on building
    # - libboost-devel
    # - libboost-python-devel
  run_constrained:
    # Make it conflict with other installations of vigra
    - vigra <0.0.0

test:
  commands:
    - test -f ${PREFIX}/lib/libvigraimpex${SHLIB_EXT}            # [unix]
    - if not exist %LIBRARY_PREFIX%\\lib\\vigraimpex.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\vigraimpex.dll exit 1  # [win]

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  license_file: LICENSE.txt
  summary: Generic Programming for Computer Vision

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
    - hmaarrfk
  feedstock-name: vigra
