{% set version = "1.12.1" %}

package:
  name: libvigra
  version: {{ version }}

source:
  url: https://github.com/ukoethe/vigra/archive/Version-{{ version.replace(".", "-") }}.tar.gz
  sha256: 8836a40a340f96ed2abf53780e883c5bf58002eb182cfccb4255b553ca48db33

build:
  number: 0
  skip: true  # [python_impl == "pypy"]
  detect_binary_files_with_prefix: true
  # There is a vigra header ./include/vigra/promote_traits.hxx.py
  # That doesn't have a meaningful pyc compilation since this is supposed
  # to be a c-package since we've disabled python compilation
  # https://github.com/conda-forge/vigra-feedstock/issues/134
  skip_compile_pyc:
    - '*'
  run_exports:
    # Seems to change ABI between minor versions
    # https://abi-laboratory.pro/index.php?view=timeline&l=vigra
    - {{ pin_subpackage('libvigra', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - make                                   # [unix]
    - python                                 # [not megabuild]
    - cross-python_{{ target_platform }}     # [(not megabuild) and (build_platform != target_platform)]
  host:
    - python                                 # [not megabuild]
    - libjpeg-turbo
    - libtiff
    - libpng
    - openexr
    - imath
    - lemon
    - fftw
    - hdf5
    - libboost-devel
    - zlib
  run_constrained:
    - {{ pin_subpackage('vigra', max_pin='x.x.x') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libvigraimpex${SHLIB_EXT}            # [unix]
    - if not exist %LIBRARY_PREFIX%\\lib\\vigraimpex.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\vigraimpex.dll exit 1  # [win]

outputs:
  - name: libvigra
  - name: vigra
    script: build_python.sh  # [unix]
    script: bld_python.bat   # [win]
    build:
      skip: true  # [python_impl == "pypy"]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pytest                                 # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - cmake
        - make                                   # [unix]
      host:
        - python
        - pytest
        - numpy
        - libjpeg-turbo
        - libtiff
        - libpng
        - openexr
        - imath
        - lemon
        - fftw
        - hdf5
        - libboost-devel
        - libboost-python-devel
        - zlib
        - {{ pin_subpackage('libvigra', exact=true) }}
      run:
        # don't pin exact due to the megabuild/non-megabuild stuff
        - {{ pin_subpackage('libvigra', max_pin='x.x.x') }}
    test:
      imports:
        - vigra


about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  license_file: LICENSE.txt
  summary: Generic Programming for Computer Vision

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
    - hmaarrfk
  feedstock-name: vigra
