{% set version = "1.11.0" %}

package:
  name: vigra
  version: {{ version }}

source:
  {% set version_tag = "Version-%s" % version.replace(".", "-") %}
  fn: vigra-{{ version_tag }}-src.tar.gz
  url: https://github.com/ukoethe/vigra/archive/{{ version_tag }}.tar.gz
  sha1: 67788d181e759e625769bf0678887718d3dc02e2

build:
  skip: true  # [win]
  number: 9
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - python
    - nose
    - numpy x.x
    - jpeg 9*
    - libtiff 4.0.*
    - libpng >=1.6.23,<1.7
    - fftw
    - hdf5 1.8.17|1.8.17.*
    - boost 1.63.*
    - zlib 1.2.*
    
  run:
    - python
    - numpy x.x
    - jpeg 9*
    - libtiff 4.0.*
    - libpng >=1.6.23,<1.7
    - fftw
    - hdf5 1.8.17|1.8.17.*
    - boost 1.63.*
    - zlib 1.2.*

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
