{% set version = "1.11.1" %}

package:
  name: vigra
  version: {{ version }}

source:
  {% set version_tag = "Version-%s" % version.replace(".", "-") %}
  fn: vigra-{{ version_tag }}-src.tar.gz
  url: https://github.com/ukoethe/vigra/archive/{{ version_tag }}.tar.gz
  sha1: 518c7a9ef0e26e39563aeebf22bcee55a7d257c8
  patches:
    ####################################################
    # Workaround for VS 2015                           #
    #                                                  #
    # xref: https://github.com/ukoethe/vigra/pull/412  #
    ####################################################
    - PR_412.diff

    ####################################################
    # Fix Windows NMake Python test run                #
    #                                                  #
    # xref: https://github.com/ukoethe/vigra/pull/417  #
    ####################################################
    - PR_417.diff

build:
  skip: true  # [win and py<35]
  number: 7
  detect_binary_files_with_prefix: true

requirements:
  build:
    - toolchain
    - cmake
    - python
    - nose
    - numpy 1.8.*   # [not (win and (py35 or py36))]
    - numpy 1.9.*   # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - jpeg 9*
    - libtiff >=4.0.8,<4.0.10
    - libpng >=1.6.32,<1.6.35
    - fftw
    - lemon
    - hdf5 1.10.1
    - boost 1.66.0
    - zlib 1.2.11
    
  run:
    - python
    - numpy >=1.8   # [not (win and (py35 or py36))]
    - numpy >=1.9   # [win and py35]
    - numpy >=1.11  # [win and py36]
    - jpeg 9*
    - libtiff >=4.0.8,<4.0.10
    - libpng >=1.6.32,<1.6.35
    - fftw
    - lemon
    - hdf5 1.10.1
    - boost 1.66.0
    - zlib 1.2.11

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  license_file: LICENSE.txt
  summary: Generic Programming for Computer Vision

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
