{% set version = "1.11.1" %}

package:
  name: vigra
  version: {{ version }}

source:
  {% set version_tag = "Version-%s" % version.replace(".", "-") %}
  fn: vigra-{{ version_tag }}-src.tar.gz
  url: https://github.com/ukoethe/vigra/archive/{{ version_tag }}.tar.gz
  sha1: 518c7a9ef0e26e39563aeebf22bcee55a7d257c8
  patches:
    # Workaround for VS 2015
    - PR_412.diff
    # Fix Windows tests
    - win_test.diff

build:
  skip: true  # [win and py<35]
  number: 0
  detect_binary_files_with_prefix: true
  features:
    - vc14               # [win and py35]
    - vc14               # [win and py36]

requirements:
  build:
    - toolchain
    - cmake
    - python
    - nose
    - numpy x.x
    - jpeg 9*
    - libtiff 4.0.*
    - libpng 1.6*
    - fftw                  # [unix]
    - hdf5 1.8.18|1.8.18.*
    - boost 1.64.*
    - zlib 1.2.*
    
  run:
    - python
    - numpy x.x
    - jpeg 9*
    - libtiff 4.0.*
    - libpng 1.6*
    - fftw                  # [unix]
    - hdf5 1.8.18|1.8.18.*
    - boost 1.64.*
    - zlib 1.2.*

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  license_file: LICENSE.txt
  summary: Generic Programming for Computer Vision

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
